/* OpenBoat console — the boards view. Loaded by console.html after the shared
   furniture; it relies on the globals defined there (state, el, api, table, pane…).
   No boat facts live here: everything on screen arrives from the API. */

/* ── view: dashboards ────────────────────────────────────────────────────────────── */
const BOARDS = [
  { id: "helm", icon: ICON.overview, url: "/index.html", title: "Helm",
    note: "The big-numeral panel: depth, wind, battery, the forecast and the chart. Built " +
          "to be read in sunlight at arm's length, with a day, dusk and night palette." },
  { id: "jobs", icon: ICON.tasks, url: "/jobs.html", title: "Jobs",
    note: "The same two lists as the Tasks page, laid out for a phone in the cockpit on a " +
          "Saturday morning rather than for a desk." },
  { id: "weather", icon: ICON.boards, url: "/windy.html", title: "Wind & weather",
    note: "The forecast on a live map, with the windows the boat's own limits allow." },
  { id: "season", icon: ICON.docs, url: "/reports/season.html", title: "Season report",
    note: "Generated by python3 -m openboat.season. Where the boat went, how long the " +
          "engine ran, what it cost." },
  { id: "engine", icon: ICON.boat, url: "/reports/engine.html", title: "Engine report",
    note: "Generated by python3 -m openboat.engine_report. Temperatures, hours, and what " +
          "the log can and cannot say." },
  { id: "snag", icon: ICON.tasks, url: null, title: "File a snag",
    note: "The phone page, on its own service and its own port — the one surface that " +
          "writes. Scan the QR it prints, or open port 8752 on this machine." },
];

function viewBoards() {
  if (state.stage) return stage(state.stage);
  const v = el("div", "view plain");
  const scroll = el("div", "scroll");
  const grid = el("div", "apps");
  BOARDS.forEach(b => {
    const c = el("button", "app-card");
    const ic = el("div", "ic"); ic.innerHTML = svg(b.icon); c.append(ic);
    c.append(el("b", "", b.title));
    c.append(el("p", "", b.note));
    c.append(el("span", "go", b.url ? "OPEN ▸" : "SEPARATE SERVICE ▸"));
    c.onclick = () => {
      if (b.url) { state.stage = b; render(); }
      else window.open(`${location.protocol}//${location.hostname}:8752/`, "_blank",
                       "noopener");
    };
    grid.append(c);
  });
  scroll.append(grid);
  v.append(scroll);
  mount(v);
}

function stage(b) {
  const v = el("div", "view solo");
  const s = el("div", "stage");
  const head = el("div", "head");
  const back = el("button", "back");
  back.innerHTML = `<svg viewBox="0 0 24 24" width="16" height="16">` +
                   `<path d="M15 5l-7 7 7 7"/></svg>Dashboards`;
  back.onclick = () => { state.stage = null; render(); };
  head.append(back);
  head.append(el("b", "", b.title));
  head.append(el("span", "path", b.url));
  const out = el("a", "", "OPEN IN A TAB ▸");
  out.href = b.url; out.target = "_blank"; out.rel = "noopener";
  head.append(out);
  s.append(head);
  const f = el("iframe");
  f.src = b.url; f.title = b.title;
  s.append(f);
  v.append(s);
  mount(v);
}

