/* OpenBoat console — the boards view. Loaded by console.html after the shared
   furniture; it relies on the globals defined there (state, el, api, table, pane…).
   No boat facts live here: everything on screen arrives from the API. */

/* An alert sitting at the bottom of a card body brings its own margin, which the body's
   padding then doubles. Used by the three views this file is loaded ahead of. */
function obFlat(n) { n.classList.remove("mb-3"); n.classList.add("mb-0"); return n; }

/* A key/value card body. The class is what lets a value with no spaces in it — a file
   path, a Signal K source — wrap instead of widening the page on a phone. */
function obKvBody(pairs) {
  const b = cardBody(kv(pairs, null));
  b.classList.add("ob-kv");
  return b;
}

/* ── view: dashboards ──────────────────────────────────────────────────────────────
   The other pages of this project, held as apps. Each has an address of its own now
   (`#boards/helm`), so a staged board survives a reload and the back button leaves it
   rather than leaving the console. */
const BOARDS = [
  { id: "helm", icon: "bi-speedometer2", url: "/index.html", title: "Helm",
    one: "The big-numeral panel, for reading in sunlight.",
    note: "Depth, wind, battery, the forecast and the chart. Built to be read at arm's " +
          "length with wet hands, with a day, dusk and night palette." },
  { id: "jobs", icon: "bi-check2-square", url: "/jobs.html", title: "Jobs",
    one: "The task list, laid out for a phone in the cockpit.",
    note: "The same two lists as the Tasks page, for a Saturday morning on the boat " +
          "rather than for a desk." },
  { id: "weather", icon: "bi-cloud-sun", url: "/windy.html", title: "Wind & weather",
    one: "The forecast on a live map.",
    note: "With the windows the boat's own limits allow marked on it." },
  { id: "season", icon: "bi-graph-up", url: "/reports/season.html", title: "Season report",
    one: "Where the boat went and what it cost.",
    note: "Generated by python3 -m openboat.season. Distance, outings, engine hours " +
          "and fuel, as far as the log can say." },
  { id: "engine", icon: "bi-thermometer-half", url: "/reports/engine.html",
    title: "Engine report",
    one: "Temperatures and hours, and the gaps in both.",
    note: "Generated by python3 -m openboat.engine_report. What the log can and cannot " +
          "say about how the engine is running." },
  { id: "snag", icon: "bi-exclamation-triangle", url: null, title: "File a snag",
    one: "The one surface in the project that writes.",
    note: "The phone page, on its own service and its own port. Scan the QR it prints, " +
          "or open port 8752 on this machine." },
];

const snagServiceUrl = () => `${location.protocol}//${location.hostname}:8752/`;

function viewBoards() {
  const staged = state.sub ? BOARDS.find(b => b.id === state.sub) : null;
  if (staged && staged.url) return boardStage(staged);
  boardsDrop();

  const page = el("div");
  if (state.sub && !staged)
    page.append(note("error", `There is no dashboard called “${state.sub}”.`));

  const grid = el("div", "row g-3");
  BOARDS.forEach(b => {
    const col = el("div", "col-md-6 col-xl-4");
    const c = el("div", "card h-100");
    const body = el("div", "card-body d-flex flex-column");

    const top = el("div", "d-flex align-items-center gap-2 mb-2");
    const ic = el("span", "fs-4 text-body-secondary lh-1");
    ic.innerHTML = `<i class="bi ${b.icon}"></i>`;
    ic.setAttribute("aria-hidden", "true");
    top.append(ic, el("h2", "h6 mb-0 fw-semibold", b.title));
    body.append(top);

    body.append(el("p", "mb-2", b.one));
    body.append(el("p", "small text-body-secondary mb-3", b.note));

    /* Two separate anchors rather than one nested in the other, because a link inside a
       link is not a thing a browser will honour: the button stages the board inside the
       console, the small link hands it to a tab of its own. */
    const foot = el("div", "mt-auto d-flex flex-wrap align-items-center gap-3");
    const go = el("a", "btn btn-primary btn-sm");
    if (b.url) {
      go.href = href("boards", b.id);
      go.textContent = "Open";
    } else {
      go.href = snagServiceUrl();
      go.target = "_blank";
      go.rel = "noopener";
      go.textContent = "Open the service";
      go.title = "The snag service runs on its own port";
    }
    foot.append(go);

    if (b.url) {
      const out = el("a", "small link-body-emphasis text-decoration-none");
      out.href = b.url;
      out.target = "_blank";
      out.rel = "noopener";
      out.title = "Open in a new tab";
      out.append(document.createTextNode("in new tab "));
      const oi = el("i", "bi bi-box-arrow-up-right");
      oi.setAttribute("aria-hidden", "true");
      out.append(oi);
      foot.append(out);
    } else {
      foot.append(el("span", "small text-body-secondary", "separate service"));
    }

    body.append(foot);
    c.append(body);
    col.append(c);
    grid.append(col);
  });
  page.append(grid);
  mount(page);
}

function boardStage(b) {
  const page = el("div");

  /* The back button and the first crumb are the same destination, which is one control
     too many only if you never use a keyboard: Esc is the third way and the crumb is
     what tells you where Esc goes. */
  const head = el("div", "d-flex flex-wrap align-items-center gap-2 mb-2");
  const back = el("a", "btn btn-sm btn-outline-secondary");
  back.href = href("boards");
  back.title = "Back to the dashboards (Esc)";
  back.setAttribute("aria-label", "Back to the dashboards");
  back.innerHTML = '<i class="bi bi-arrow-left"></i>';
  head.append(back);
  head.append(crumbs([{ label: "Dashboards", href: href("boards") }, { label: b.title }]));
  head.append(el("span", "small text-body-secondary font-monospace d-none d-md-inline",
                 b.url));

  const out = el("a", "btn btn-sm btn-outline-secondary ms-auto");
  out.href = b.url; out.target = "_blank"; out.rel = "noopener";
  out.append(document.createTextNode("Open in a tab "));
  const oi = el("i", "bi bi-box-arrow-up-right");
  oi.setAttribute("aria-hidden", "true");
  out.append(oi);
  head.append(out);
  page.append(head);

  const f = el("iframe", "w-100 border rounded ob-stage");
  f.src = b.url; f.title = b.title;
  page.append(f);
  mount(page);

  /* Esc leaves a staged board, the same way it leaves an overlay. The shell handles Esc
     for overlays; a view handles it for its own detail page.

     One handler, replaced rather than added to. Staging a board is a re-render like any
     other, so registering here without dropping the last one meant a handler per visit:
     five trips through a board left five of them waiting on the same key. */
  boardsDrop();
  boardsEsc = e => {
    if (e.key !== "Escape" || overlay()) return;
    if (state.view !== "boards" || !state.sub) { boardsDrop(); return; }
    boardsDrop();
    nav("boards");
  };
  document.addEventListener("keydown", boardsEsc);
}

let boardsEsc = null;
function boardsDrop() {
  if (!boardsEsc) return;
  document.removeEventListener("keydown", boardsEsc);
  boardsEsc = null;
}
