/* OpenBoat console — the boards view. Loaded by console.html after the shared
   furniture; it relies on the globals defined there (state, el, api, table, pane…).
   No boat facts live here: everything on screen arrives from the API. */

/* ── view: dashboards ──────────────────────────────────────────────────────────────
   The other pages of this project, held as apps. Each has an address of its own now
   (`#boards/helm`), so a staged board survives a reload and the back button leaves it
   rather than leaving the console. */
const BOARDS = [
  { id: "helm", icon: ICON.overview, url: "/index.html", title: "Helm",
    one: "The big-numeral panel, for reading in sunlight.",
    note: "Depth, wind, battery, the forecast and the chart. Built to be read at arm's " +
          "length with wet hands, with a day, dusk and night palette." },
  { id: "jobs", icon: ICON.tasks, url: "/jobs.html", title: "Jobs",
    one: "The task list, laid out for a phone in the cockpit.",
    note: "The same two lists as the Tasks page, for a Saturday morning on the boat " +
          "rather than for a desk." },
  { id: "weather", icon: ICON.boards, url: "/windy.html", title: "Wind & weather",
    one: "The forecast on a live map.",
    note: "With the windows the boat's own limits allow marked on it." },
  { id: "season", icon: ICON.docs, url: "/reports/season.html", title: "Season report",
    one: "Where the boat went and what it cost.",
    note: "Generated by python3 -m openboat.season. Distance, outings, engine hours " +
          "and fuel, as far as the log can say." },
  { id: "engine", icon: ICON.boat, url: "/reports/engine.html", title: "Engine report",
    one: "Temperatures and hours, and the gaps in both.",
    note: "Generated by python3 -m openboat.engine_report. What the log can and cannot " +
          "say about how the engine is running." },
  { id: "snag", icon: ICON.tasks, url: null, title: "File a snag",
    one: "The one surface in the project that writes.",
    note: "The phone page, on its own service and its own port. Scan the QR it prints, " +
          "or open port 8752 on this machine." },
];

const snagServiceUrl = () => `${location.protocol}//${location.hostname}:8752/`;

function viewBoards() {
  const staged = state.sub ? BOARDS.find(b => b.id === state.sub) : null;
  if (staged && staged.url) return boardStage(staged);
  boardsDrop();

  const v = el("div", "view plain");
  const scroll = el("div", "scroll");
  if (state.sub && !staged)
    scroll.append(note("error", `There is no dashboard called “${state.sub}”.`));

  const grid = el("div", "apps");
  BOARDS.forEach(b => {
    const c = el("div", "app-card");
    const top = el("div", "top");
    const ic = el("div", "ic"); ic.innerHTML = svg(b.icon);
    top.append(ic);

    /* The whole card opens the board; the small link opens it in a tab of its own. Two
       separate anchors rather than one nested in the other, because a link inside a link
       is not a thing a browser will honour. */
    const out = el("a", "tab", "NEW TAB ▸");
    out.href = b.url || snagServiceUrl();
    out.target = "_blank";
    out.rel = "noopener";
    out.title = b.url ? "Open in a new tab" : "Open the snag service in a new tab";
    top.append(out);
    c.append(top);

    const face = el("a", "face");
    face.href = b.url ? href("boards", b.id) : snagServiceUrl();
    if (!b.url) { face.target = "_blank"; face.rel = "noopener"; }
    face.append(el("b", "", b.title));
    c.append(face);

    c.append(el("p", "one", b.one));
    c.append(el("p", "", b.note));
    c.append(el("span", "go", b.url ? "OPEN ▸" : "SEPARATE SERVICE ▸"));
    grid.append(c);
  });
  scroll.append(grid);
  v.append(scroll);
  mount(v);
}

function boardStage(b) {
  const v = el("div", "view solo");
  const s = el("div", "stage");
  const head = el("div", "head");

  /* The chevron is the back link and the first crumb is the same destination spelled
     out, which is one control too many only if you never use a keyboard: Esc is the
     third way and the crumb is what tells you where Esc goes. */
  const back = el("a", "back");
  back.href = href("boards");
  back.innerHTML = `<svg viewBox="0 0 24 24" width="16" height="16">` +
                   `<path d="M15 5l-7 7 7 7"/></svg>`;
  back.title = "Back to the dashboards (Esc)";
  back.setAttribute("aria-label", "Back to the dashboards");
  head.append(back);
  head.append(crumbs([{ label: "Dashboards", href: href("boards") }, { label: b.title }]));
  head.append(el("span", "path", b.url));

  const out = el("a", "", "OPEN IN A TAB ▸");
  out.href = b.url; out.target = "_blank"; out.rel = "noopener";
  head.append(out);
  s.append(head);

  const f = el("iframe");
  f.src = b.url; f.title = b.title;
  s.append(f);
  v.append(s);
  mount(v);

  /* Esc leaves a staged board, the same way it leaves an overlay. The shell handles Esc
     for overlays; a view handles it for its own detail page.

     One handler, replaced rather than added to. Staging a board is a re-render like any
     other, so registering here without dropping the last one meant a handler per visit:
     five trips through a board left five of them waiting on the same key. */
  boardsDrop();
  boardsEsc = e => {
    if (e.key !== "Escape" || $(".ob-veil")) return;
    if (state.view !== "boards" || !state.sub) { boardsDrop(); return; }
    boardsDrop();
    nav("boards");
  };
  document.addEventListener("keydown", boardsEsc);
}

let boardsEsc = null;
function boardsDrop() {
  if (!boardsEsc) return;
  document.removeEventListener("keydown", boardsEsc);
  boardsEsc = null;
}
